services:
  web:
    image: nginx
    ports:
      - "85:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php-fpm:
    build: docker/php
    volumes:
      - .:/var/www/html
  postgres_db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "54324:5432"






